import './style.css';
import { createNamoIDClient } from '@namoidhq/js';

const DEMO_USER = { sub: 'demo-riya', name: 'Riya Mehta', email: 'riya@northstar.test' };
const seed = [
  { id:'act_1042', type:'Refund', title:'Issue a partial refund', target:'Order #NS-4821 · Aisha Khan', amount:'$250.00', risk:'High', requestedBy:'Support Copilot', status:'pending', expiresAt:Date.now()+1000*60*18, details:'Customer received the wrong shade. Refund the item value to the original payment method.', createdAt:Date.now()-1000*60*4, actor:'agent.support', audit:[['Proposal created','Support Copilot','4 min ago']] },
  { id:'act_1041', type:'Address change', title:'Update delivery address', target:'Order #NS-4798 · Marco Silva', amount:'', risk:'Medium', requestedBy:'Ops Copilot', status:'approved', expiresAt:Date.now()+1000*60*7, details:'Change delivery destination before warehouse handoff.', createdAt:Date.now()-1000*60*22, actor:'agent.ops', audit:[['Proposal created','Ops Copilot','22 min ago'],['Approved','Riya Mehta','19 min ago']] },
  { id:'act_1039', type:'Data export', title:'Export support history', target:'Aisha Khan · 90-day window', amount:'', risk:'High', requestedBy:'Insights Copilot', status:'executed', expiresAt:Date.now()-1000*60*40, details:'Generate a synthetic support history export for the account owner.', createdAt:Date.now()-1000*60*90, actor:'agent.insights', audit:[['Proposal created','Insights Copilot','1 hr ago'],['Approved','Riya Mehta','56 min ago'],['Executed','Riya Mehta','40 min ago']] }
];
let actions = JSON.parse(localStorage.getItem('guardrail_actions') || 'null') || seed;
let user = JSON.parse(sessionStorage.getItem('guardrail_user') || 'null');
let selected = actions[0]?.id; let filter = 'all';
const clientId = import.meta.env.VITE_NAMOID_CLIENT_ID;
const namoid = clientId ? createNamoIDClient({ clientId }) : null;

function save(){ localStorage.setItem('guardrail_actions', JSON.stringify(actions)); }
function relative(ts){ const m=Math.max(0,Math.round((Date.now()-ts)/60000)); return m<1?'just now':m<60?`${m} min ago`:`${Math.round(m/60)} hr ago`; }
function initials(name){ return name.split(' ').map(x=>x[0]).slice(0,2).join(''); }
function statusLabel(s){ return ({pending:'Needs review',approved:'Approved',rejected:'Rejected',expired:'Expired',executed:'Executed'})[s]||s; }
function riskClass(r){ return r.toLowerCase(); }

function render(){
  const visible=actions.filter(a=>filter==='all'||a.status===filter); const active=actions.find(a=>a.id===selected)||visible[0]||actions[0]; if(active) selected=active.id;
  document.querySelector('#app').innerHTML=`
  <div class="shell">
    <aside class="rail"><div class="brand"><div class="brand-mark">G</div><div><b>Guardrail</b><span>INBOX</span></div></div><div class="workspace"><span class="overline">Workspace</span><strong>Northstar Beauty</strong><span class="muted">Operations team</span></div>
      <nav><button class="nav-active">▣ <span>Approval inbox</span><em>${actions.filter(a=>a.status==='pending').length}</em></button><button>◷ <span>Activity log</span></button><button>⚙ <span>Workspace settings</span></button></nav>
      <div class="rail-bottom"><div class="powered">POWERED BY <b>NamoID</b><small>Independent community build<br>Not an official NamoID product</small></div>${user?`<button class="profile" id="logout"><span class="avatar">${initials(user.name||'User')}</span><span><b>${user.name||'Signed-in user'}</b><small>${user.email||'Authenticated session'}</small></span><i>↗</i></button>`:''}</div>
    </aside>
    <main><header class="topbar"><div><span class="overline">MONDAY · 14 OCTOBER 2024</span><h1>Approval inbox</h1></div><div class="top-actions"><span class="secure">◉ Authenticated session</span><button class="ghost" id="new-action">+ Simulate agent request</button></div></header>
      ${!user?`<section class="auth-banner"><div><span class="eyebrow">NamoID Hosted Auth</span><h2>Sign in to review sensitive actions</h2><p>Your identity is verified by the application's Hosted Auth flow. Demo mode is available for local evaluation.</p></div><button class="primary" id="signin">${namoid ? 'Sign in with NamoID':'Enter demo workspace'}</button></section>`:''}
      <section class="stats"><div><span class="stat-label">Awaiting decision</span><b>${actions.filter(a=>a.status==='pending').length}</b><small class="amber">● Needs your attention</small></div><div><span class="stat-label">Approved today</span><b>${actions.filter(a=>a.status==='approved'||a.status==='executed').length}</b><small>Across all agents</small></div><div><span class="stat-label">Blocked attempts</span><b>02</b><small class="red">↗ Tamper or replay</small></div><div class="stat-note"><span class="quote">“</span><p>Agents can propose.<br><b>People decide.</b></p></div></section>
      <div class="content-grid"><section class="inbox"><div class="section-head"><div><span class="eyebrow">LIVE QUEUE</span><h2>Requests <span>${visible.length}</span></h2></div><select id="filter"><option value="all">All requests</option><option value="pending">Needs review</option><option value="approved">Approved</option><option value="executed">Executed</option></select></div><div class="request-list">${visible.map(a=>card(a)).join('')}</div></section>${active?detail(active):'<section class="detail empty">Select a request to inspect it.</section>'}</div>
      <footer><span>Guardrail Inbox · A focused proof of concept for human-in-the-loop AI actions</span><a href="https://github.com/namoidhq/namoid-challenges" target="_blank">Challenge source ↗</a></footer>
    </main></div>`;
  bind();
}
function card(a){ return `<button class="request ${a.id===selected?'selected':''}" data-id="${a.id}"><div class="request-top"><span class="type-dot ${riskClass(a.risk)}"></span><span class="type">${a.type}</span><span class="time">${relative(a.createdAt)}</span></div><h3>${a.title}</h3><p>${a.target}</p><div class="request-foot"><span class="status ${a.status}">${statusLabel(a.status)}</span><span class="risk ${riskClass(a.risk)}">${a.risk} risk</span></div></button>`; }
function detail(a){ const expired=a.status==='approved'&&a.expiresAt<Date.now(); if(expired){a.status='expired';save();} return `<section class="detail"><div class="detail-head"><div><span class="eyebrow">REQUEST ${a.id}</span><h2>${a.title}</h2><p>${a.details}</p></div><span class="status large ${a.status}">${statusLabel(a.status)}</span></div><div class="identity-strip"><span class="avatar agent">✦</span><div><small>PROPOSED BY</small><b>${a.requestedBy}</b><span>Authenticated agent identity · ${a.actor}</span></div><span class="arrow">→</span><div><small>DECISION OWNER</small><b>${user?.name||'Not signed in'}</b><span>${user?'NamoID application session':'Sign in required'}</span></div></div><div class="facts"><div><small>ACTION</small><b>${a.type}</b></div><div><small>TARGET</small><b>${a.target}</b></div><div><small>${a.amount?'AMOUNT':'WINDOW'}</small><b>${a.amount||'Single-use request'}</b></div><div><small>EXPIRES</small><b>${a.status==='pending'||a.status==='approved'?`${Math.max(0,Math.round((a.expiresAt-Date.now())/60000))} min remaining`:'Closed'}</b></div></div><div class="integrity"><span>⌁</span><div><b>Action integrity locked</b><p>This approval is bound to the exact proposal. Any change to amount, destination, or target invalidates it.</p></div><code>SHA-256 · ${a.id.slice(-4)}…7c91</code></div><div class="audit"><div class="section-head"><div><span class="eyebrow">DECISION TRAIL</span><h3>Audit history</h3></div><span class="private">◉ Payload-free log</span></div>${a.audit.map(x=>`<div class="audit-row"><span class="audit-line"></span><span><b>${x[0]}</b><small>${x[1]} · ${x[2]}</small></span></div>`).join('')}</div>${a.status==='pending'?`<div class="decision-bar"><button class="reject" data-action="reject">Reject</button><button class="edit" data-action="edit">Edit proposal</button><button class="approve" data-action="approve">Approve action <span>⌘ ↵</span></button></div>`:a.status==='approved'?`<div class="decision-bar"><button class="reject" data-action="tamper">Test tamper block</button><button class="approve" data-action="execute">Execute approved action</button></div>`:`<div class="notice ${a.status}">${a.status==='executed'?'✓ Executed once. Replay attempts are blocked.':'This request is closed and cannot be reused.'}</div>`}</section>`; }
function bind(){ document.querySelectorAll('[data-id]').forEach(x=>x.onclick=()=>{selected=x.dataset.id;render()}); document.querySelector('#filter')?.addEventListener('change',e=>{filter=e.target.value;render()}); document.querySelector('#signin')?.addEventListener('click',async()=>{ if(namoid){ const started=await namoid.hostedAuth.start({redirectUri:location.origin+location.pathname+'auth/callback'});sessionStorage.setItem('namoid_transaction',JSON.stringify(started.transaction));location.assign(started.authorizationUrl); } else {user=DEMO_USER;sessionStorage.setItem('guardrail_user',JSON.stringify(user));render();} }); document.querySelector('#logout')?.addEventListener('click',()=>{user=null;sessionStorage.removeItem('guardrail_user');render()}); document.querySelector('#new-action')?.addEventListener('click',()=>{actions.unshift({id:'act_'+Math.floor(Math.random()*900+1100),type:'Refund',title:'Prepare a customer refund',target:'Order #NS-4902 · Demo customer',amount:'$75.00',risk:'Medium',requestedBy:'Support Copilot',status:'pending',expiresAt:Date.now()+1000*60*20,details:'Agent proposes a goodwill refund for a delayed shipment.',createdAt:Date.now(),actor:'agent.support',audit:[['Proposal created','Support Copilot','just now']]});save();selected=actions[0].id;render()}); document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>decide(b.dataset.action)); }
function decide(kind){const a=actions.find(x=>x.id===selected);if(!a)return;if(kind==='edit'){a.details+=' Human requested a smaller amount; original proposal retained for comparison.';a.amount='$125.00';a.audit.push(['Edited before approval',user?.name||'Demo reviewer','just now']);}if(kind==='approve'){if(!user){alert('Sign in with NamoID before approving.');return}a.status='approved';a.audit.push(['Approved',user.name,'just now']);}if(kind==='reject'){a.status='rejected';a.audit.push(['Rejected',user?.name||'Demo reviewer','just now']);}if(kind==='execute'){a.status='executed';a.audit.push(['Executed',user?.name||'Demo reviewer','just now']);}if(kind==='tamper'){a.status='rejected';a.audit.push(['Blocked · action hash mismatch','Guardrail system','just now']);}save();render();}
async function callback(){ if(!namoid||!location.pathname.includes('auth/callback'))return; const tx=JSON.parse(sessionStorage.getItem('namoid_transaction')||'null'); const url=new URL(location.href); try{ if(!tx||url.searchParams.get('state')!==tx.state)throw Error('Invalid authorization state');const tokens=await namoid.hostedAuth.exchangeCode({code:url.searchParams.get('code'),redirectUri:tx.redirectUri,codeVerifier:tx.codeVerifier});user=await namoid.hostedAuth.userInfo(tokens.access_token);sessionStorage.setItem('guardrail_user',JSON.stringify(user));sessionStorage.removeItem('namoid_transaction');history.replaceState({},'', '/');render(); }catch(e){document.querySelector('#app').innerHTML=`<div class="error-state"><h1>Sign-in could not be completed</h1><p>${e.message}</p><a href="/">Return to inbox</a></div>`;} }
callback(); render();
